Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -8,18 +8,16 @@ jobs:
       - image: circleci/node:10
     steps:
       - checkout
-      - node/with-cache:
-          steps:
-            - run: npm install typescript
-            - sonarcloud/scan
-            - run:
-                command: |
-                  STATUS=$(curl -u "${SONAR_TOKEN}:" https://sonarcloud.io/api/qualitygates/project_status?projectKey=kura2020_public2 | jq -r '.projectStatus.status')
-                  echo "Status of SonarQube task is ${STATUS} "
-                  if [ "${STATUS}" != "OK" ]; then
-                      echo "Quality gate is not OK - exiting with error"
-                      # exit 1
-                  fi
+      - run: npm install typescript
+      - sonarcloud/scan
+      - run:
+          command: |
+            STATUS=$(curl -u "${SONAR_TOKEN}:" https://sonarcloud.io/api/qualitygates/project_status?projectKey=kura2020_public2 | jq -r '.projectStatus.status')
+            echo "Status of SonarQube task is ${STATUS} "
+            if [ "${STATUS}" != "OK" ]; then
+                echo "Quality gate is not OK - exiting with error"
+                # exit 1
+            fi
 workflows:
     build-and-test:
       jobs:
